config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :name, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter:nav_menu
  
  def nav_menu
    @pages = Page.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :find_page, only: [:edit, :update, :show, :destroy]
  def new
    @page = Page.new
  end
  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end
  def index
    @pages = Page.all
  end
  def edit

  end
  def update
    if @page.update(page_params)
      redirect_to pages_path
    else
      render :edit
    end
  end
  def show
    
  end
  def destroy
    if @page.destroy
      redirect_to pages_path
    else
      redirect_to pages_path, error: 'Не получилось удалить страницу'
    end
  end
  private
    def page_params
      params[:page].permit(:name, :description)
    end
    def find_page
      @page = Page.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @title = 'Сергей Уколов'
  end

  def about
    @title = 'Обо мне'
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="header">
        <div class="container">
          <ul class="nav">
            <li><%= link_to 'Страницы', pages_path %></li>

            <% @pages.each do |page| %>
            <li><%= link_to page.name, page_path(page) %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="container">
        <%= yield %>
      </div>
  </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for @page do |f| %>
<%= f.error_notification  %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

app/views/pages/edit.html.erb
<h1>Редактировать</h1>

<%= render 'form' %>

app/views/pages/index.html.erb
<h1>Страници</h1>
<table border="1">
  <thead>
    <tr>
      <td>Название</td>
      <td>Редактировать</td>
      <td>Удалить</td>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.name %></td>
      <td><%= link_to 'Edit', edit_page_path(page) %></td>
      <td><%= link_to 'Destroy', page_path(page), method: :delete, data: {confirm: 'Вы уверенны?'} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Создать', new_page_path %>

app/views/pages/new.html.erb
<h1>Новая страница</h1>
<%= render 'form' %>

app/views/pages/show.html.erb
<h1><%= @page.name %></h1>
<h4><%= @page.description %></h4>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>hello</h1>
<%= @title %>